dist: xenial
language: python
cache: pip
sudo: required

matrix:
    fast_finish: true
    include:
        - python: 3.7

install:
    - pip install -U pip
    - pip install -U black flake8 pytest pytest-cov codecov mypy sphinx

script:
    # Mypy
    - mypy .

    # Unit tests
    - pytest --cov dragn

    # Static analysis
    - flake8 --statistics --count

    # Code formatting
    - black --exclude docs --check .

after_success:
    # Send coverage to Codecov
    - codecov
